language: node_js

node_js:
  - "6"
  - "7"
  - "node"

sudo: false

env:
    - HAPI_VERSION="@13"
    - HAPI_VERSION="@14"
    - HAPI_VERSION="@15"
    - HAPI_VERSION=""

install:
    - npm install
    - npm install hapi$HAPI_VERSION
